### ISSUE TITLE
2022年11月29号  fun218 = matchObj_fun218[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by miaozhenchao** [codeM78/zzu_jksb-daily#10]
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    msg = daka.sign_in(id=id, pwd=pwd, name=str(id), check_today=0)
  File "/root/daka.py", line 118, in sign_in
    fun218 = matchObj_fun218[0]
IndexError: list index out of range

27日晚上更新过之后可以正常打卡，28日与29日均报这个错误，我看了看网站上表单的name发现没有fun218这个值，想请教一下这个值是怎么来的，麻烦您还有空的时候回复一下我吧 谢谢您了

**Comment by 233333LSSSSSSSS** [comment]
同问，一直打卡失败..

**Comment by 233333LSSSSSSSS** [comment]
同问，更新之后，Actions每次运行都要10分钟以上，而且打卡失败...

**Comment by codeM78** [comment]
最近失败是fun218被弃用了，目前daka.py已经修复

**Comment by codeM78** [comment]
10分钟以上，是因为打卡脚本设置了失败重试。一直再重试中
