### ISSUE TITLE
恢复打卡

### ISSUE THREAD

**Issue by codeM78** [codeM78/zzu_jksb-daily#7]
恢复到最初的模样，更新仓库后，打卡依旧

**Comment by Sun1ght** [comment]
提示打卡错误检查是否有验证码，这里应该怎么处理

**Comment by codeM78** [comment]
请重新fork最新仓库~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月16日(星期五) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeM78/zzu_jksb-daily] 恢复打卡 (Issue #7)





 
提示打卡错误检查是否有验证码，这里应该怎么处理

**Comment by codeM78** [comment]
请不要再随意Pull requestsl啦

**Comment by Sun1ght** [comment]
...
我不太会不好意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月17日(星期六) 晚上10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codeM78/zzu_jksb-daily] 恢复打卡 (Issue #7)





 
请不要再随意Pull requestsl啦
